### ISSUE TITLE
Style undo/redo buttons when clicked

### ISSUE THREAD

**Issue by yujiatay** [travellingsalesmanco/muvement#38]

**Comment by JayPeeTeeDee** [comment]
The following only shows up if you try to click undo when there is no undo state. On desktop/laptop the grey box shows up on hover. It is Antd's indication that the undo button is disabled.
![image](https://user-images.githubusercontent.com/25446629/47949938-cabf9e00-df85-11e8-8a9f-ec336ef3a022.png)
